---
- name: "Create VLAN"
  hosts: all
  gather_facts: no

  tasks:
    - name: Show VLAN
      cisco.ios.ios_command:
        commands:
          - show vlan
      register: show_vlan

    - name: Display VLAN information
      debug:
        msg: "{{ show_vlan.stdout_lines }}"